from collections import namedtuple

# Namedtuple representing a song.
Lyric = namedtuple("Lyric", ["lyric", "song"])

LYRICS = [
    Lyric("I thought that I was dreaming when you said you love me", "Ivy"),
    Lyric("If I could see through walls, I could see you're faking. If you could see my thoughts, you would see our faces", "Ivy"),
    Lyric("I ain't a kid no more, we'll never be those kids again", "Ivy"),
    Lyric("I broke your heart last week, you'll probably feel better by the weekend", "Ivy"),
    Lyric("Said she need a ring like Carmelo, you must be on that white like Othello", "Nikes"),
    Lyric("I mean my balls stickin' to my jeans", "Nikes"),
    Lyric("Living so the last night feels like a past life", "Nikes"),
    Lyric("I'm not him, but I'll mean something to you", "Nikes"),
    Lyric("It's hell on Earth and the city's on fire. Inhale, in hell there's heaven", "Solo"),
    Lyric("In comes the morning haunting us with the beams, solstice ain't as far as it used to be.", "Skyline To"),
    Lyric("Summer's not as long as it used to be, every day counts like crazy", "Skyline To"),
    Lyric("Poolside convooooooooo, about your summer last night", "Self Control"),
    Lyric("I'll be the boyfriend in your wet dreams tonight", "Self Control"),
    Lyric("You cut your hair, but you used to live a BLONDED life", "Self Control"),
    Lyric("Wish I was there, wish we'd grown up on the same advice and our time was right", "Self Control"),
    Lyric("I, I, I KNOW YOU GOTTA LEAVE, LEAVE, LEAVE......", "Self Control"),
    Lyric("I know you don't need me right now, and to you it's just a late night out", "Good Guy"),
    Lyric("Although you got beaucoup family, you don't even got nobody bein' honest with you", "Nights"),
    Lyric("If I get my money right you know I won't need you", "Nights"),
    Lyric("Did you call me from a séance? You are from my past life. Hope you're doin' well, bruh", "Nights"),
    Lyric("Time to start your day, bruh", "Nights"),
    Lyric("Wanna see nirvana, but don't wanna die yet", "Nights"),
    Lyric("Rollin' marijuana, that's a cheap vacation", "Nights"),
    Lyric("Rollin' marijuana, that's a cheap vacation", "Nights"),
    Lyric("Shut the fuck up, I don't want your conversation", "Nights"),
    Lyric("Still got some good nights memorized. And the look back's gettin' me right", "Nights"),
    Lyric("Every night fucks every day up. Every day patches the night up", "Nights"),
    Lyric("No white lighters 'til I fuck my 28th up", "Nights"),
    Lyric("Bad luck to talk on these rides", "White Ferrari"),
    Lyric("Mind on the road, your dilated eyes watch the clouds float", "White Ferrari"),
    Lyric("I didn't care to state the plain. Kept my mouth closed. We're both so familiar", "White Ferrari"),
    Lyric("Stick by me, close by me. You were fine, you were fine here", "White Ferrari"),
    Lyric("I care for you still and I will forever. That was my part of the deal, honest", "White Ferrari"),
    Lyric("I'm sure we're taller in another dimension. You say we're small and not worth the mention", "White Ferrari"),
    Lyric("But we're so okay here, we're doing fine. Primal and naked, you dream of walls that hold us in prison. "
          "It's just a skull, least that's what they call it and we're free to roam.", "White Ferrari"),
    Lyric("I couldn't gauge your fears. I can't relate to my peers", "Seigfried"),
    Lyric("I'd rather live outside. I'd rather chip my pride than lose my mind out here", "Seigfried"),
    Lyric("Maybe I'm a fool. Maybe I should move and settle. Two kids and a swimming pool. I'm not brave", "Seigfried"),
    Lyric("Been living in an idea. An idea from another man's mind", "Seigfried"),
    Lyric("Maybe I'm a fool. To settle for a place with some nice views", "Seigfried"),
    Lyric("I'd rather live outside. I'd rather go to jail. I've tried hell", "Seigfried"),
    Lyric("This is not my life. It's just a fond farewell to a friend", "Seigfried"),
    Lyric("Dreaming a thought that could dream about a thought that could think of the dreamer that thought that could "
          "think of dreaming and getting a glimmer of God. I be dreaming of dreaming a thought that could dream about a"
          " thought that could think of dreaming a dream where I cannot, where I cannot", "Seigfried"),
    Lyric("Less morose and more present. Dwell on my gifts for a second, a moment", "Seigfried"),
    Lyric("One solar flare, we're consumed, so why not spend this flammable paper on the film that's my life?", "Seigfried"),
    Lyric("I'd do anything for you.. in the dark", "Seigfried"),
    Lyric("There will be mountains you won't move. Still, I'll always be there for you", "Godspeed"),
    Lyric("This love will keep us through blinding of the eyes, silence in the ears, darkness of the mind", "Godspeed"),
    Lyric("If I was being honest. I'd say long as I could fuck three times a day and not skip a meal, I'm good", "Futura Free"),
    Lyric("I'll keep quiet and let you run your phone bill up. I know you love to talk", "Futura Free"),
    Lyric("You must ain't get the memo. I don't cuff bitches no more, but your bitch my exception", "Futura Free"),
    Lyric("Ménage on my birthday, tap out on the first stroke", "Futura Free"),
    Lyric("Both nuts weigh two pounds, all on your bitch like futons", "U-N-I-T-Y"),
]
